[package]
name = "migrations"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/migrations.rs"
doctest = false

[dependencies]
refinery = { version = "0.8.12", features = ["tokio-postgres", "postgres"] }
tokio-postgres = "0.7.10"
futures = "0.3.30"
anyhow = "1.0.80"
tokio = "1.36.0"
