[package]
name = "migrations"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/migrations.rs"
doctest = false

[dependencies]
refinery = { version = "0.8.12", features = ["tokio-postgres", "postgres"] }
log = "0.4.20"
tokio-postgres = "0.7.10"
