[package]
name = "idp"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
common = { workspace = true }
database = { workspace = true }

actix-web = "4.5.1"
