[package]
name = "database"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
sqlx = { version = "0.7", features = [ "runtime-tokio", "postgres" ] }
anyhow = "1.0.80"
futures-util = "0.3.30"
async-trait = "0.1.77"
